language: perl6
perl6:
  - latest

install:
  - git clone https://github.com/google/gumbo-parser.git
  - echo $PWD
  - ( cd gumbo-parser && ./autogen.sh && ./configure --prefix=$HOME/gumbo-parser && make install-exec )
  - rm -rf gumbo-parser
  - echo $PWD
  - rakudobrew build-panda
  - panda --notests installdeps .
script:
  - LD_LIBRARY_PATH=$HOME/gumbo-parser/lib panda install .
  - PERL6LIB=$PWD/blib/lib LD_LIBRARY_PATH=$HOME/gumbo-parser/lib prove -e perl6 -vr t/
sudo: false
